name: AWS CDK Deployment

on:
  push:
    branches:
      - main
env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  aws_cdk:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
      # Step 1: Lint and test (customize as needed)      
        run: npm install

      - name: Lint and test
        #run: npm run lint && npm test
        run: npm test
  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          ## the following creates an ARN based on the values entered into github secrets
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: myGitHubActions

      # Step 2: Deploy using AWS CDK
      - name: CDK Diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'diff'
          actions_comment: true
        env:
          CERT_ARN: ${{secrets.CERT_ARN}}
        #env:
        #  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #  AWS_DEFAULT_REGION: 'us-east-1'

      - name: CDK Deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'AwsRssReaderStack'
          cdk_args: '--require-approval never'
          actions_comment: false
        #env:
        #  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #  AWS_DEFAULT_REGION: 'us-east-1'

      # Step 3: Synthesize (optional)
      #- name: CDK Synth
      #  uses: youyo/aws-cdk-github-actions@v2
      #  with:
      #    cdk_subcommand: 'synth'
      #    cdk_version: '2.137.0'
      #    working_dir: 'src'
        #env:
        #  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #  AWS_DEFAULT_REGION: 'us-east-1'
